version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=postgres://postgres.wppdnhxmzixfhxqsydor:RV3bxxocMfinqakN@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    ports:
      - "7000:7000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
